
/*  injector.h public API of the library */
#pragma once
#include <windows.h>

typedef enum _INJECT_STATUS {
	INJECT_OK = 0,
	INJECT_ERR_NTDLL_INIT,
	INJECT_ERR_OPEN_PROCESS,
	INJECT_ERR_RESOLVE_LOADLIBRARY,
	INJECT_ERR_ALLOC,
	INJECT_ERR_WRITE,
	INJECT_ERR_CREATE_THREAD,
	INJECT_ERR_THREAD_TIMEOUT,
} INJECT_STATUS;

INJECT_STATUS InjectDll(DWORD pid, LPCWSTR dllPath);
